name: Mend

on: workflow_dispatch

jobs:
  call-template:
    uses: tabacmend-up-sandbox/mend-templates/.github/workflows/mend-scan-template.yaml@main
    with:
      SCA: true
      SAST: true
      CN: false
      SCA_Reports: 'ALL'